### ISSUE TITLE
As an ISL user, I want to see a list of dog profiles, so I can learn about them

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/paw#14]

**Comment by alxmrtnz** [comment]
- [ ] Dogs separated into checked in and not checked in
- [ ] Checked in dogs in grouped by check in status (In Office, On a walk, Missing)
- [ ] Not checked in dog shown in disable state
- [ ] Not checked in dog: on hover, change opacity to normal, denoting to user that they can update status to checked in here
- [ ] Dynamic date
