### ISSUE TITLE
As an ISL member, I want to login, so I can access the paw application

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/paw#2]
- [x] Use OAuth for handling authentication

**Comment by akrawchyk** [comment]
This should be good to go. The only catch is you can still login with a non-ISL email, however you will not be granted access to the paw application. Still looking in to restricting auth to only ISL emails.

**Comment by samyabehary** [comment]
Working with an ISL login. Error message looks good for non-ISLers.
