### ISSUE TITLE
As an ISL user, I want to land on the dashboard after login, so I can start using the paw application

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/paw#7]

**Comment by akrawchyk** [comment]
This is implemented with google auth.

**Comment by samyabehary** [comment]
Does the google authentication only allow users with an ISL email address to login? Or any gmail address?

**Comment by akrawchyk** [comment]
It allows anyone to sign in with Google Auth, but will only allow access to ISL email addresses. We should consider adding an error message somewhere notifying other visitors they are not allowed access.

If we want to restrict access to only the ISL Google Apps domain, we'll need to follow these instructions https://support.google.com/a/answer/1668854?hl=en.

**Comment by samyabehary** [comment]
Got it. I don't feel super strongly about error message vs. restricting access, so whichever you think is easiest to implement works.

**Comment by akrawchyk** [comment]
An error message is much easier than restricting access. I'll make an issue for that.
