### ISSUE TITLE
As an ISL user, I want to see a map of active dogs in the office, so I can locate each dog

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/paw#8]

**Comment by JulianGindi** [comment]
I'm thinking about changing the payload sent to the Paw-API to be something like such:

```
event: {
  "deviceID": "someDeviceID",
  "location": "kitchen",
  "timestamp": "someUnixTimeStamp"
}
```

We will specify each Hydrant's "location" by setting an environment variable on the device itself
